server:
  port: 8088
  tomcat:
    max-threads: 50
ssl-enable: false
camunda:
  rest:
    api:
      url: http://bpmn-infra:8081/engine-rest/engine/
      engine: default
      auth: Basic YWRtaW46S3A4Yko0U1hzek0wV1hsaGFrM2VIbGNzZTJnQXc4NHZhb0dHbUp2VXkyVQ==
mso:
  database:
    rest:
      api:
        url: http://so-request-db-adapter:8083/infraActiveRequests/
        auth: Basic YnBlbDpwYXNzd29yZDEk
spring:

    main:

      allow-bean-definition-overriding: true

    security:

      usercredentials:

      -                                         

        username: gui

        password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'

        role: GUI-Client