version: '2'
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU}
services:
################################################################################
  mariadb:
    image: mariadb:10.1.11
    ports:
      - "3306"
    volumes:
      - ./volumes/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./volumes/mariadb/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    hostname:
      mariadb.so.testlab.onap.org
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
################################################################################
  catalog-db-adapter:
    image: so/catalog-db-adapter
    ports:
      - "8082:8082"
    volumes:
      - ./volumes/so/ca-certificates/onapheat:/app/ca-certificates
      - ./volumes/so/config/catalog-db-adapter/onapheat:/app/config
    environment:
      - APP=catalog-db-adapter
      - JVM_ARGS=-Xms64m -Xmx512m
      - DB_HOST=mariadb
#     - KEYSTORE=msoClientKeyStore-onapheat.jks
#     - KEYSTORE_PASSWORD=password
#     - TRUSTSTORE=msoTrustStore.jks
#     - TRUSTSTORE_PASSWORD=password
    hostname:
      catalog-db-adapter.so.testlab.onap.org
    depends_on:
      - mariadb
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    command:
      - /app/wait-for.sh
      - -q
      - -t
      - "300"
      - mariadb:3306
      - --
      - "/app/start-app.sh"
################################################################################
  request-db-adapter:
    image: so/request-db-adapter
    ports:
      - "8083:8083"
    volumes:
      - ./volumes/so/ca-certificates/onapheat:/app/ca-certificates
      - ./volumes/so/config/request-db-adapter/onapheat:/app/config
    environment:
      - APP=request-db-adapter
      - JVM_ARGS=-Xms64m -Xmx512m
      - DB_HOST=mariadb
#     - KEYSTORE=msoClientKeyStore-onapheat.jks
#     - KEYSTORE_PASSWORD=password
#     - TRUSTSTORE=msoTrustStore.jks
#     - TRUSTSTORE_PASSWORD=password
    hostname:
      request-db-adapter.so.testlab.onap.org
    depends_on:
      - mariadb
      - catalog-db-adapter
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    command:
      - /app/wait-for.sh
      - -q
      - -t
      - "300"
      - catalog-db-adapter:8082
      - --
      - "/app/start-app.sh"
################################################################################
  sdnc-adapter:
    image: so/sdnc-adapter
    ports:
      - "8090:8086"
    volumes:
      - ./volumes/so/ca-certificates/onapheat:/app/ca-certificates
      - ./volumes/so/config/sdnc-adapter/onapheat:/app/config
    environment:
      - APP=sdnc-adapter
      - JVM_ARGS=-Xms64m -Xmx512m
      - DB_HOST=mariadb
#     - KEYSTORE=msoClientKeyStore-onapheat.jks
#     - KEYSTORE_PASSWORD=password
#     - TRUSTSTORE=msoTrustStore.jks
#     - TRUSTSTORE_PASSWORD=password
    hostname:
      sdnc-adapter.so.testlab.onap.org
    depends_on:
      - mariadb
      - catalog-db-adapter
      - request-db-adapter
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    command:
      - /app/wait-for.sh
      - -q
      - -t
      - "300"
      - request-db-adapter:8083
      - --
      - "/app/start-app.sh"
################################################################################
  openstack-adapter:
    image: so/openstack-adapter
    ports:
      - "8087:8087"
    volumes:
      - ./volumes/so/ca-certificates/onapheat:/app/ca-certificates
      - ./volumes/so/config/openstack-adapter/onapheat:/app/config
    environment:
      - APP=openstack-adapter
      - JVM_ARGS=-Xms64m -Xmx512m
      - DB_HOST=mariadb
#     - KEYSTORE=msoClientKeyStore-onapheat.jks
#     - KEYSTORE_PASSWORD=password
#     - TRUSTSTORE=msoTrustStore.jks
#     - TRUSTSTORE_PASSWORD=password
    hostname:
      openstack-adapter.so.testlab.onap.org
    depends_on:
      - mariadb
      - catalog-db-adapter
      - request-db-adapter
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    command:
      - /app/wait-for.sh
      - -q
      - -t
      - "300"
      - request-db-adapter:8083
      - --
      - "/app/start-app.sh"
################################################################################
  vfc-adapter:
    image: so/vfc-adapter
    ports:
      - "8084:8084"
    volumes:
      - ./volumes/so/ca-certificates/onapheat:/app/ca-certificates
      - ./volumes/so/config/vfc-adapter/onapheat:/app/config
    environment:
      - APP=vfc-adapter
      - JVM_ARGS=-Xms64m -Xmx512m
      - DB_HOST=mariadb
#     - KEYSTORE=msoClientKeyStore-onapheat.jks
#     - KEYSTORE_PASSWORD=password
#     - TRUSTSTORE=msoTrustStore.jks
#     - TRUSTSTORE_PASSWORD=password
    hostname:
      vfc-adapter.so.testlab.onap.org
    depends_on:
      - mariadb
      - catalog-db-adapter
      - request-db-adapter
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    command:
      - /app/wait-for.sh
      - -q
      - -t
      - "300"
      - request-db-adapter:8083
      - --
      - "/app/start-app.sh"
################################################################################
  asdc-controller:
    image: so/asdc-controller
    ports:
      - "8085:8085"
    volumes:
      - ./volumes/so/ca-certificates/onapheat:/app/ca-certificates
      - ./volumes/so/config/asdc-controller/onapheat:/app/config
    environment:
      - APP=asdc-controller
      - JVM_ARGS=-Xms64m -Xmx512m
      - DB_HOST=mariadb
#     - KEYSTORE=msoClientKeyStore-onapheat.jks
#     - KEYSTORE_PASSWORD=password
#     - TRUSTSTORE=msoTrustStore.jks
#     - TRUSTSTORE_PASSWORD=password
    hostname:
      asdc-controller.so.testlab.onap.org
    depends_on:
      - mariadb
      - catalog-db-adapter
      - request-db-adapter
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    command:
      - /app/wait-for.sh
      - -q
      - -t
      - "300"
      - request-db-adapter:8083
      - --
      - "/app/start-app.sh"
################################################################################
  bpmn-infra:
    image: so/bpmn-infra
    ports:
      - "8081:8081"
    volumes:
      - ./volumes/so/ca-certificates/onapheat:/app/ca-certificates
      - ./volumes/so/config/bpmn-infra/onapheat:/app/config
    environment:
      - APP=bpmn-infra
      - JVM_ARGS=-Xms64m -Xmx512m
      - DB_HOST=mariadb
#     - KEYSTORE=msoClientKeyStore-onapheat.jks
#     - KEYSTORE_PASSWORD=password
#     - TRUSTSTORE=msoTrustStore.jks
#     - TRUSTSTORE_PASSWORD=password
    hostname:
      bpmn-infra.so.testlab.onap.org
    depends_on:
      - mariadb
      - catalog-db-adapter
      - request-db-adapter
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    command:
      - /app/wait-for.sh
      - -q
      - -t
      - "300"
      - request-db-adapter:8083
      - --
      - "/app/start-app.sh"
################################################################################
  api-handler-infra:
    image: so/api-handler-infra
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/so/ca-certificates/onapheat:/app/ca-certificates
      - ./volumes/so/config/api-handler-infra/onapheat:/app/config
    environment:
      - APP=api-handler-infra
      - JVM_ARGS=-Xms64m -Xmx512m
      - DB_HOST=mariadb
#     - KEYSTORE=msoClientKeyStore-onapheat.jks
#     - KEYSTORE_PASSWORD=password
#     - TRUSTSTORE=msoTrustStore.jks
#     - TRUSTSTORE_PASSWORD=password
    hostname:
      api-handler-infra.so.testlab.onap.org
    depends_on:
      - mariadb
      - catalog-db-adapter
      - request-db-adapter
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    command:
      - /app/wait-for.sh
      - -q
      - -t
      - "300"
      - request-db-adapter:8083
      - --
      - "/app/start-app.sh"
