server:
  port: ${CONTAINER_PORT}
  tomcat:
    max-threads: 50
ssl-enable: false
camunda:
  rest:
    api:
      url: http://so-bpmn-infra.${COMMON_NAMESPACE}:8081/sobpmnengine/engine/
      engine: default
      auth: Basic YXBpaEJwbW46cGFzc3dvcmQxJA==
mso:
  database:
    rest:
      api:
        url: http://so-request-db-adapter.${COMMON_NAMESPACE}:8083/infraActiveRequests/
        auth: Basic YnBlbDpwYXNzd29yZDEk
