logging:
  path: logs

#spring:
#  datasource:
#     hikari:
#       driver-class-name: org.mariadb.jdbc.Driver
#       jdbcUrl: jdbc:mariadb://mariadb:3306/requestdb
#       username: requestuser
#       password: request123
#       pool-name: reqdb-pool
#       registerMbeans: true

server:
    port: 9012
    tomcat:
        max-threads: 50
#mso:
#  site-name: localSite
#  adapters:
#    requestDb:
#      endpoint: http://cnf-adapter:8083
#      auth: Basic YnBlbDpwYXNzd29yZDEk

#Actuator
spring:
  security:
    usercredentials:
    -
      username: apihBpmn
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: BPMN-Client
    -
      username: sdncaBpmn
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: BPMN-Client
    -
      username: poBpmn
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: BPMN-Client
    -
      username: wmaBpmn
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: BPMN-Client
    -
      username: sniro
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: SNIRO-Client
    -
      username: mso_admin
      password: '$2a$10$Fh9ffgPw2vnmsghsRD3ZauBL1aKXebigbq3BB1RPWtE62UDILsjke'
      role: ACTUATOR
