logging:
  path: logs

spring:
  datasource:
     driver-class-name: org.mariadb.jdbc.Driver
     url: jdbc:mariadb://mariadb:3306/requestdb
     username: requestuser
     password: request123
     dbcp2:
      initial-size: 5
      max-total: 20
      validation-query: select 1
      test-on-borrow: true
  security:
     usercredentials:
     -
      username: bpel
      password: '$2a$12$1xyutEZNfjGewIZRfKaE8eZE99f5sYFUmmM80BobI65KNjmcK0JuO'
      role: BPEL-Client
     -
      username: mso_admin
      password: '$2a$12$tidKuu.h88E2nuL95pTVY.ZOYMN/1dp29A9b1o.0GFDsVVSYlMkHa'
      role: ACTUATOR

server:
    port: 8084
    tomcat:
        max-threads: 50
mso:
  site-name: localSite
  adapters:
    requestDb:
      endpoint: http://request-db-adapter:8083
      auth: Basic YnBlbDpwYXNzd29yZDEk

#Actuator
management:
  security:
    enabled: false
    basic:
      enabled: false
